mysql:
  MYSQL_DATABASE: breeze
  MYSQL_HOSTNAME: 192.168.0.109
  MYSQL_PORT: 3306
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: senha3
ldap:
  LDAP_HOST: breeze-ldap
  LDAP_BIND_DN: dc=brisa,dc=io
  LDAP_BIND_PASSWORD: ldappassword
  LDAP_BIND_USERNAME: admin