services:
  nginx:
    image: nginx:latest
    container_name: breeze-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /certs:/certs
      - ./files/default.conf:/etc/nginx/conf.d/default.conf
  api:
    image: alpine:latest
    container_name: breeze-api
    restart: always
    ports:
      - 5000:5000
    command: |
      sh -c "
        apk update ;
        apk add python3 py3-pip ;
        apk add build-base openldap-dev python3-dev ;
        pip install flask python-ldap mysql-connector-python pyyaml ldap3 flask-cors ;
        cd /app ;
        python3 main.py"
    volumes:
      - .:/app
  ldap:
    image: osixia/openldap:1.5.0
    container_name: breeze-ldap
    restart: always
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: Brisa
      LDAP_DOMAIN: brisa.io
      LDAP_ADMIN_PASSWORD: ldappassword
